name: Overseer

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ windows-latest ]
        # os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: Run tests
      run: |
        go version
        make test
